export LIBP2P_MDNS_SERVICE_NAME = _bar._tcp.local

chat_bar:
	@echo "Running chat-bar"
	cargo run --bin chat-bar

basic:
	@echo "Running basic"
	cargo run --bin basic

nested_groups:
	@echo "Running nested_groups"
	cargo run --bin nested_groups

build:
	@echo "Building chat_bar"
	cargo build --release

install:
	@echo "Installing chat_bar"
	cargo install --path .
