export LIBP2P_MDNS_SERVICE_NAME = _bar._tcp.local

run:
	@echo "Running chat-bar"
	cargo run

build:
	@echo "Building chat-bar"
	cargo build --release

install:
	@echo "Installing chat-bar"
	cargo install --path .
